import Cocoa

/// What to do when a given system cursor is on screen.
enum CursorAction: Equatable {
    /// Draw this cursor from the asset manifest.
    case cat(String)
    /// Let the real system pointer show through.
    ///
    /// Used for the drag badges, where the badge itself carries the meaning --
    /// a green plus means copy, a grey cross means the item disappears if you
    /// let go. Replacing those with a cat would throw the information away, and
    /// getting `disappearingItem` wrong is destructive.
    case system
}

/// Maps a recognised system cursor to the artwork that replaces it.
///
/// Kept separate from the reference table on purpose: the table records what
/// each cursor *looks like* and is regenerated by calibration, while this is a
/// product decision about what to show instead.
enum CursorPolicy {
    static let actions: [String: CursorAction] = [
        "arrow": .cat("arrow"),
        "iBeam": .cat("text"),
        "iBeamVertical": .cat("text"),
        "pointingHand": .cat("click"),
        "crosshair": .cat("precision"),
        "operationNotAllowed": .cat("unavailable"),
        // NSCursor.resizeLeftRight / .resizeUpDown are the split-view divider
        // cursors. Dragging a window edge uses a different, private set, so both
        // families have to be mapped or half the resize cases go unrecognised.
        "resizeLeftRight": .cat("horizontal"),
        "resizeLeft": .cat("horizontal"),
        "resizeRight": .cat("horizontal"),
        "windowResizeEastWest": .cat("horizontal"),
        "windowResizeEast": .cat("horizontal"),
        "windowResizeWest": .cat("horizontal"),
        "resizeUpDown": .cat("vertical"),
        "resizeUp": .cat("vertical"),
        "resizeDown": .cat("vertical"),
        "windowResizeNorthSouth": .cat("vertical"),
        "windowResizeNorth": .cat("vertical"),
        "windowResizeSouth": .cat("vertical"),
        "openHand": .cat("move"),
        "closedHand": .cat("move"),
        "resizeNWSE": .cat("diagonal1"),
        "resizeNESW": .cat("diagonal2"),
        "dragCopy": .system,
        "dragLink": .system,
        "contextualMenu": .system,
        "disappearingItem": .system,
    ]
}

/// Reference fingerprints captured by Scripts/calibrate, used to recognise the
/// live cursor.
struct CursorTable {
    struct Entry {
        let name: String
        let width: Int
        let height: Int
        let hotspotX: Int
        let hotspotY: Int
        let fingerprint: [UInt8]
    }

    let side: Int
    let entries: [Entry]

    /// Above this, a match is not trusted and the real cursor is left alone.
    /// Exact matches score 0 -- the window server hands back byte-identical
    /// bitmaps -- so anything appreciably above zero means the reading is not
    /// something calibration ever saw.
    private static let maximumDistance = 2.0

    static func load() -> CursorTable? {
        guard let url = resourceURL(),
              let data = try? Data(contentsOf: url),
              let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let side = root["side"] as? Int,
              let raw = root["cursors"] as? [[String: Any]]
        else { return nil }

        let entries: [Entry] = raw.compactMap { item in
            guard let name = item["name"] as? String,
                  let width = item["width"] as? Int,
                  let height = item["height"] as? Int,
                  let hotspotX = item["hotspotX"] as? Int,
                  let hotspotY = item["hotspotY"] as? Int,
                  let numbers = item["fingerprint"] as? [Int]
            else { return nil }
            return Entry(name: name, width: width, height: height,
                         hotspotX: hotspotX, hotspotY: hotspotY,
                         fingerprint: numbers.map { UInt8(clamping: $0) })
        }
        guard !entries.isEmpty else { return nil }
        return CursorTable(side: side, entries: entries)
    }

    /// Where calibration writes its result.
    ///
    /// Not into the app bundle: that is code-signed, and writing to it would
    /// invalidate the signature.
    static func userTableURL() -> URL {
        let support = FileManager.default.urls(for: .applicationSupportDirectory,
                                               in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSHomeDirectory())
        return support
            .appendingPathComponent("CatCursor")
            .appendingPathComponent("cursor_table.json")
    }

    static var hasUserTable: Bool {
        FileManager.default.fileExists(atPath: userTableURL().path)
    }

    private static func resourceURL() -> URL? {
        var candidates: [URL] = []
        // A table calibrated on this machine always wins: the bundled one was
        // captured on whatever macOS the release was built on.
        candidates.append(userTableURL())
        if let bundled = Bundle.main.resourceURL {
            candidates.append(bundled.appendingPathComponent("cursor_table.json"))
        }
        let executableDirectory = Bundle.main.bundleURL.deletingLastPathComponent()
        candidates.append(executableDirectory.appendingPathComponent("cursor_table.json"))
        candidates.append(executableDirectory
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Resources/cursor_table.json"))
        return candidates.first { FileManager.default.fileExists(atPath: $0.path) }
    }

    /// Recognises a live reading, or returns nil when nothing matches closely.
    ///
    /// Geometry is a hard filter first. It cleanly separates artwork that is
    /// nearly identical at fingerprint resolution, and -- importantly -- it
    /// fails wholesale if the accessibility pointer-size setting has changed
    /// since calibration, at which point every cursor falls back to the real
    /// one rather than being guessed at.
    func match(_ reading: SystemCursorReading) -> String? {
        let live = SystemCursorReader.fingerprint(reading.image, side: side)
        let pool = entries.filter {
            $0.width == Int(reading.size.width) && $0.height == Int(reading.size.height)
                && $0.hotspotX == Int(reading.hotspot.x)
                && $0.hotspotY == Int(reading.hotspot.y)
        }
        guard !pool.isEmpty else { return nil }

        var best: (name: String, distance: Double)?
        for entry in pool {
            let d = Self.distance(live, entry.fingerprint)
            if best == nil || d < best!.distance { best = (entry.name, d) }
        }
        guard let best, best.distance <= Self.maximumDistance else { return nil }
        return best.name
    }

    private static func distance(_ a: [UInt8], _ b: [UInt8]) -> Double {
        guard a.count == b.count, !a.isEmpty else { return .infinity }
        var total = 0
        for index in 0..<a.count { total += abs(Int(a[index]) - Int(b[index])) }
        return Double(total) / Double(a.count)
    }
}
